#USO DA CONDIÇÃO DISTINCT

SELECT EMBALAGEM, TAMANHO FROM tabela_de_produtos;

SELECT DISTINCT EMBALAGEM, TAMANHO 
FROM tabela_de_produtos;

SELECT DISTINCT EMBALAGEM, TAMANHO 
FROM tabela_de_produtos WHERE sabor = 'Laranja';

SELECT DISTINCT EMBALAGEM, TAMANHO, SABOR, PRECO_DE_LISTA
FROM tabela_de_produtos WHERE sabor = 'Laranja';

-- QUAIS OS BAIRROS DA CIDADE DO RIO DE JANEIRO 
-- QUE POSSUEM CLIENTES?
SELECT DISTINCT BAIRRO, ESTADO, CIDADE
FROM tabela_de_clientes 
WHERE cidade = 'Rio de Janeiro';

#USO DA CONDIÇÃO LIMIT

SELECT * FROM tabela_de_produtos LIMIT 2;

-- OBTENHA AS 10 PRIMEIRAS VENDAS
-- DO DIA 01/01/2017
SELECT * FROM notas_fiscais 
WHERE data_venda = '2017-01-01' LIMIT 5,10;

