#Aula 18/03/2026 - Gerando Relatório de Vendas

-- RELATÓRIO DE VENDAS VÁLIDAS

/*Gerência da área de vendas da empresa de suco de frutas
quer um relatório que mostre dentre todas as vendas, quais delas 
foram válidas e quais delas foram inválidas */

/*1º Obter o volume total de vendas 
para cada cliente dentro de 1 mês */

select * from notas_fiscais;
select * from itens_notas_fiscais;

-- Junção das duas tabelas com JOIN
SELECT NF.CPF, NF.DATA_VENDA, INF.QUANTIDADE  
FROM NOTAS_FISCAIS AS NF
INNER JOIN ITENS_NOTAS_FISCAIS AS INF
ON NF.NUMERO = INF.NUMERO;

-- Isolando o ano e mês
SELECT NF.CPF, DATE_FORMAT(NF.DATA_VENDA, '%Y-%m' ) AS ANO_MES, 
INF.QUANTIDADE  
FROM NOTAS_FISCAIS AS NF
INNER JOIN ITENS_NOTAS_FISCAIS AS INF
ON NF.NUMERO = INF.NUMERO;

-- Agrupar e Somar o campo quantidade
SELECT NF.CPF, DATE_FORMAT(NF.DATA_VENDA, '%Y-%m') AS ANO_MES, 
SUM(INF.QUANTIDADE) AS QNTD_VENDAS  
FROM NOTAS_FISCAIS AS NF
INNER JOIN ITENS_NOTAS_FISCAIS AS INF
ON NF.NUMERO = INF.NUMERO
GROUP BY NF.CPF,DATE_FORMAT(NF.DATA_VENDA, '%Y-%m');

/*Obter o limite de volume total de compra
por cliente*/
SELECT * FROM TABELA_DE_CLIENTES AS TC;

SELECT TC.CPF, TC.NOME, TC.VOLUME_DE_COMPRA
FROM TABELA_DE_CLIENTES AS TC;

-- JOIN para juntar tabela_de_cliente a outra consulta
SELECT NF.CPF,TC.NOME, 
DATE_FORMAT(NF.DATA_VENDA, '%Y-%m') AS ANO_MES, 
SUM(INF.QUANTIDADE) AS QNTD_VENDAS,
TC.VOLUME_DE_COMPRA AS QNTD_LIMITE
FROM NOTAS_FISCAIS AS NF
INNER JOIN ITENS_NOTAS_FISCAIS AS INF
ON NF.NUMERO = INF.NUMERO
INNER JOIN TABELA_DE_CLIENTES AS TC
ON TC.CPF = NF.CPF
GROUP BY NF.CPF,TC.NOME,DATE_FORMAT(NF.DATA_VENDA, '%Y-%m');

-- Subquery
SELECT X.CPF, X.NOME, X.ANO_MES, X.QNTD_VENDAS, X.QNTD_LIMITE,
ABS(X.QNTD_LIMITE - X.QNTD_VENDAS) AS DIFERENCA,
CASE
	WHEN (X.QNTD_LIMITE - X.QNTD_VENDAS) < 0
    THEN "Volume Excedido"
    ELSE "Volume Adequado"
END AS STATUS_VENDA
FROM (
SELECT NF.CPF, TC.NOME, 
DATE_FORMAT(NF.DATA_VENDA, '%Y-%m') AS ANO_MES, 
SUM(INF.QUANTIDADE) AS QNTD_VENDAS,
TC.VOLUME_DE_COMPRA AS QNTD_LIMITE
FROM NOTAS_FISCAIS AS NF
INNER JOIN ITENS_NOTAS_FISCAIS AS INF
ON NF.NUMERO = INF.NUMERO
INNER JOIN TABELA_DE_CLIENTES AS TC
ON TC.CPF = NF.CPF
GROUP BY NF.CPF,TC.NOME,DATE_FORMAT(NF.DATA_VENDA, '%Y-%m')) AS X;